### ISSUE TITLE
Can't run tests with django.contrib.sites in INSTALLED_APPS

### ISSUE THREAD

**Issue by bigeye** [django-nonrel/django-nonrel#3]
I'm using mongodb in django with django-nonrel, djangotoolbox, mongodb-engine packages.

When trying to execute "python manage.py test [[app-name]]", I got the exception like below.

``` python
$ python2.7 manage.py test [[app-name]]                                                                                                        
Traceback (most recent call last):
  File "manage.py", line 14, in <module>
    execute_manager(settings)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 438, in execute_manager
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 379, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 191, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 220, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/commands/test.py", line 37, in handle
    failures = test_runner.run_tests(test_labels)
  File "/usr/local/lib/python2.7/site-packages/django/test/simple.py", line 359, in run_tests
    old_config = self.setup_databases()
  File "/usr/local/lib/python2.7/site-packages/django/test/simple.py", line 296, in setup_databases
    test_db_name = connection.creation.create_test_db(self.verbosity, autoclobber=not self.interactive)
  File "/usr/local/lib/python2.7/site-packages/django_mongodb_engine-0.4.0-py2.7.egg/django_mongodb_engine/creation.py", line 151, in create_test_db
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 166, in call_command
    return klass.execute(*args, **defaults)  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 220, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 351, in handle
    return self.handle_noargs(**options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/commands/syncdb.py", line 109, in handle_noargs
    emit_post_sync_signal(created_models, verbosity, interactive, db)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/sql.py", line 190, in emit_post_sync_signal
    interactive=interactive, db=db)
  File "/usr/local/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 172, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/usr/local/lib/python2.7/site-packages/django/contrib/sites/management.py", line 21, in create_default_site
    s.save(using=db)
  File "/usr/local/lib/python2.7/site-packages/django/contrib/sites/models.py", line 51, in save
    super(Site, self).save(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 462, in save
    self.save_base(using=using, force_insert=force_insert, force_update=force_update)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 573, in save_base
    result = manager._insert(values, return_id=update_pk, using=using)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/manager.py", line 195, in _insert
    return insert_query(self.model, values, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 1438, in insert_query
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/lib/python2.7/site-packages/djangotoolbox/db/basecompiler.py", line 350, in execute_sql
    value = self.convert_value_for_db(db_type, value)
  File "/usr/local/lib/python2.7/site-packages/django_mongodb_engine-0.4.0-py2.7.egg/django_mongodb_engine/compiler.py", line 66, in wrapper
  File "/usr/local/lib/python2.7/site-packages/django_mongodb_engine-0.4.0-py2.7.egg/django_mongodb_engine/compiler.py", line 302, in convert_value_for_db
bson.errors.InvalidId: AutoField (default primary key) values must be strings representing an ObjectId on MongoDB (got u'1' instead). Please make sure your SITE_ID contains a valid ObjectId string.
```

I think the code which causes the exception is in [django/contrib/sites/management.py#L20](https://github.com/django-nonrel/django-nonrel/blob/develop/django/contrib/sites/management.py#L20). The pk value should not be set by 1.
- I'm using django-nonrel development version(for using django 1.3.1) and django-mongodb-engine 0.4.0 and djangotoolbox 0.9.2.

**Comment by jonashaag** [comment]
Remove `'django.contrib.sites'` from your `INSTALLED_APPS`.

**Comment by wrwrwr** [comment]
Do I read it right that contrib.sites does not work with MongoDB? As far as I can tell it does work with GAE.

**Comment by jonashaag** [comment]
It works but not in tests because Django tries to create a `pk=1` Site which can't work.

Someone needs to fix that in Django vanilla.

**Comment by wrwrwr** [comment]
``` python
# with testapp + GAE
from django.contrib.sites.models import *
Site(pk=1, domain="example.com", name="example.com")
<Site: example.com>
```

After reading http://django-mongodb.org/troubleshooting.html, I think I'm lost even more as to the reasons why it can't be fixed in the back-end :-)

**Comment by wrwrwr** [comment]
To be more specific, why not handle int keys? Something like below, but with a less hackish way of recognizing ints and some way of converting them to objectids that best would guarantee not to clash with anything.

``` diff
diff --git a/django_mongodb_engine/compiler.py b/django_mongodb_engine/compiler.py
index b5baa5e..9801e24 100644
--- a/django_mongodb_engine/compiler.py
+++ b/django_mongodb_engine/compiler.py
@@ -284,6 +284,14 @@ class SQLCompiler(NonrelCompiler):
             return [self.convert_value_for_db(db_type, val) for val in value]

         if db_type == 'objectid':
+
+            # Convert int to a valid ObjectId.
+            if isinstance(value, unicode) and len(value) != 12:
+                try:
+                    value = 'int:{0:08d}'.format(int(value))
+                except ValueError:
+                    pass
+
             try:
                 return ObjectId(value)
             except InvalidId:
@@ -325,7 +333,11 @@ class SQLCompiler(NonrelCompiler):
                             for key, subvalue in value.iteritems())

         if db_type == 'objectid':
-            return unicode(value)
+            value = unicode(value)
+            if value[:4] == 'int:':
+                value = int(value[4:])
+
+            return value

         if db_type == 'date':
             return datetime.date(value.year, value.month, value.day)
```

Was there maybe some discussion of the "int key" problem that I've missed?

**Comment by jonashaag** [comment]
Allowing ints as primary keys might be an option, but I don't think it's a good idea to have workarounds around the Django int PK limitation and at the same time fight against integer PK assumptions in other places...

**Comment by mgmtech** [comment]
I addressed this by disconnecting the post_syncdb signal and replacing it with one which uses my settings.SITE_ID,  basically a copy of the original found in the django source. 

IDK if this is a good solution or if it will create additional issues, but its what I am using ATM.

settings.INSTALLED_APPS += ('testsetup',)

settings.SITE_ID = u'4f800202932'

here is my testsetup/management.py

``` python
# -*- coding: utf-8 -*-
"""
Override the default behavior of the sites model to acommodate MongoDB
"""
from django.conf import settings
from django.db.models import signals
from django.db import router
from django.contrib.sites.models import Site
from django.contrib.sites import models as site_app
from django.contrib.sites.management import create_default_site

def mongo_create_default_site(app, created_models, verbosity, db, **kwargs):
    # Only create the default sites in databases where Django created the table
    if Site in created_models and router.allow_syncdb(db, Site) :
        if verbosity >= 2:
            print "Creating example.com Site object"
        # The default settings set SITE_ID = 1, and some tests in Django's test
        # suite rely on this value. However, if database sequences are reused
        # (e.g. in the test suite after flush/syncdb), it isn't guaranteed that
        # the next id will be 1, so we coerce it. See #15573 and #16353. This
        # can also crop up outside of tests - see #15346.
        s = Site(pk=settings.SITE_ID, domain="example.com", name="Example")
        s.save(using=db)
    Site.objects.clear_cache()

# disconnect the previous signal
signals.post_syncdb.disconnect(create_default_site, sender=site_app)
signals.post_syncdb.connect(mongo_create_default_site, sender=site_app)
```

**Comment by silviomoreto** [comment]
The pull request solved the issue?
